name: "CI"

on: ["push", "pull_request"]

jobs:
  code-quality:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v5"

      - name: "Set up Rust toolchain"
        uses: "actions-rust-lang/setup-rust-toolchain@v1"
        with:
          components: clippy, rustfmt

      - name: "Check formatting"
        run: "cargo fmt --all --check"

      - name: "Run clippy"
        run: "cargo clippy -- -Dwarnings"

      - name: "Run tests"
        run: "cargo test"
